export const enum Strings {
    BORDER_BOX = 'border-box',
    D = 'd',
    FILL = 'fill',
    GRADIENT_TRANSFORM = 'gradientTransform',
    GRADIENT_UNITS = 'gradientUnits',
    HIDDEN = 'hidden',
    ID = 'id',
    LINEAR_GRADIENT = 'linearGradient',
    NONE = 'none',
    OFFSET = 'offset',
    PATH = 'path',
    PX = 'px',
    ROTATE = 'rotate',
    STOP = 'stop',
    STOP_COLOR = 'stop-color',
    STROKE = 'stroke',
    STROKE_COLOR = 'stroke-color',
    STROKE_WIDTH = 'stroke-width',
    SVG_NS = 'http://www.w3.org/2000/svg',
    URL = 'url',
    USER_SPACE_ON_USE = 'userSpaceOnUse'
}
